framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json

        transports:
            sync:
                dsn: 'sync://'
                serializer: messenger.transport.symfony_serializer
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer

when@test:
    framework:
        messenger:
            transports:
                sync: 'in-memory://'
                async: 'in-memory://'
